# Dependencies
markdown: kramdown
highlighter: rouge
future: true

plugins:
    - jekyll-sitemap

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, new_draft.sh]

# Permalinks
permalink: /:title/

# Site
title: 'WebAssembly Weekly'
description: 'A community-driven weekly newsletter about WebAssembly'
baseurl: https://wasmweekly.news
logo: /img/logo.png

twitter:
    username: WasmWeekly

curator:
    name: 'Colin Eberhardt'
    url: https://twitter.com/ColinEberhardt

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/feed.xml'
    twitter: 'https://twitter.com/WasmWeekly'
    github: 'https://github.com/ColinEberhardt/WasmWeekly'
    issue: 'https://github.com/ColinEberhardt/WasmWeekly/issues/new'
    pull: 'https://github.com/ColinEberhardt/WasmWeekly/compare'
